# Generated by Django 3.2 on 2021-04-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('ubication', models.CharField(max_length=30, verbose_name='Dirección')),
                ('cellphone', models.CharField(max_length=15, unique=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo')),
                ('eps', models.CharField(max_length=20, verbose_name='Eps')),
                ('rh', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='Rh')),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.educationlevel', verbose_name='Nivel educativo')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('report', models.CharField(max_length=15, verbose_name='reporte')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.activitytype', verbose_name='Tipo de actividad')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.patient', verbose_name='Paciente')),
            ],
        ),
    ]
